src/Entity/Wtype.php
<?php

namespace App\Entity;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Table;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Index;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WtypeRepository")
 * @UniqueEntity(fields="label", message="Label is already taken.")
 */
class Wtype
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $label;

 

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer", options={"default":0},nullable=true)
     */
    private $status;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $activation_civile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $activation_scolaire;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $introduction;


    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $introduction_ouvert;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $introduction_ferme;

    /**
     * @ORM\Column(type="boolean",options={"default":0})
     */
    private $actif;
    

     /**
     * @ORM\OneToMany(targetEntity="App\Entity\Wconf", mappedBy="wconf_typcont")
     * @ORM\JoinColumn( name="wtype_wconf", referencedColumnName="wconf_typcont", nullable=true, onDelete="SET NULL"))
     */
    private $wtype_wconf;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comptes_demo;
    
    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $introduction_ouvert_complement;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $message_rappel_coordonnees;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $message_rappel_declaration;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $message_rappel_introduction;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $departement;

    /**
     * @ORM\Column(type="integer")
     */
    private $priorite;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $contact_email;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $contact_email2;
    
    /**
     * @ORM\Column(type="boolean",options={"default":0})
     */
    private $send_validation_email;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $declaration_aide;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email_signature;

    /**
     * @ORM\Column(type="integer")
     */
    private $archive;

    /**
     * @ORM\Column(type="integer")
     */
    private $archive_ouverture;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $historique_intro_civile;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $historique_intro_scolaire;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $proformat_intro;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $proformat_confirmation;
    

    

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $validation_confirm_message;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $label_interface;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $label_interface_home;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $type_interface;

    
    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Wtype", inversedBy="contrats_propositions")
     * @ORM\JoinTable(name="wtype__contrats_propositions",
     *   joinColumns={
     *     @ORM\JoinColumn(name="id", referencedColumnName="id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="wtype_id", referencedColumnName="id")
     *   }
     * )
     */
    private $contrats_propositions;
    
    /**
     * {@inheritdoc}
     */
    public function addContratsPropositions(?ContentInterface $contrats_propositions)
    {
        $this->contrats_propositions[] = $contrats_propositions;
    }
    
    /**
     * {@inheritdoc}
     */
    public function getContratsPropositions()
    {
        return $this->contrats_propositions;
    }
    
    
    /**
     * {@inheritdoc}
     */
    public function setContratsPropositions($contrats_propositions = false)
    {
        $this->contrats_propositions = $contrats_propositions;
    }
    
    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $concon_propsition_contrat_label;
    
    
    public function getConconPropsitionContratLabel(): ?string
    {
        return $this->concon_propsition_contrat_label;
    }
    
    public function setConconPropsitionContratLabel(?string $concon_propsition_contrat_label): self
    {
        $this->concon_propsition_contrat_label = $concon_propsition_contrat_label;
    
        return $this;
    }
    
    
    
    
    public function __construct()
    {
        //$this->type = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getLabel();
    }
    
    public function unsetId()
    {
        $this->id=null;
    } 
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    /**
     * @return Collection|Wdeclar[]
     */
    public function getTypes(): Collection
    {
        return $this->types;
    }

    public function addTypes(Wdeclar $type): self
    {
        if (!$this->types->contains($type)) {
            $this->types[] = $type;
            $types->setWdeTypcont($this);
        }

        return $this;
    }

    public function removeTypes(Wdeclar $types): self
    {
        if ($this->types->contains($types)) {
            $this->types->removeElement($types);
            // set the owning side to null (unless already changed)
            if ($types->getWdeTypcont() === $this) {
                $types->setWdeTypcont(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }


    public function getActivationCivile(): ?string
    {
        return $this->activation_civile;
    }

    public function setActivationCivile(?string $activation_civile): self
    {
        $this->activation_civile = $activation_civile;

        return $this;
    }

    public function getActivationScolaire(): ?string
    {
        return $this->activation_scolaire;
    }

    public function setActivationScolaire(?string $activation_scolaire): self
    {
        $this->activation_scolaire = $activation_scolaire;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(?string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }



    public function getIntroductionOuvert(): ?string
    {
        return $this->introduction_ouvert;
    }

    public function setIntroductionOuvert(?string $introduction_ouvert): self
    {
        $this->introduction_ouvert = $introduction_ouvert;

        return $this;
    }

    public function getIntroductionFerme(): ?string
    {
        return $this->introduction_ferme;
    }

    public function setIntroductionFerme(?string $introduction_ferme): self
    {
        $this->introduction_ferme = $introduction_ferme;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }
    
    
   /**
     * @return Collection|Wconf[]
     */
    public function getWtypeWconf(): Collection
    {
        return $this->wtype_wconf;
    }

    public function addWtypeWconf(Wdeclar $WtypeWconf): self
    {
        if (!$this->wtype_wconf->contains($WtypeWconf)) {
            $this->wtype_wconf[] = $WtypeWconf;
            $types->setWconfTypcont($this);
        }

        return $this;
    }

    public function removeWtypeWconf(Wdeclar $WtypeWconf): self
    {
        if ($this->wtype_wconf->contains($WtypeWconf)) {
            $this->wtype_wconf->removeElement($WtypeWconf);
            // set the owning side to null (unless already changed)
            if ($WtypeWconf->getWconfTypcont() === $this) {
                $WtypeWconf->setWconfTypcont(null);
            }
        }

        return $this;
    }

    public function getComptesDemo(): ?string
    {
        return $this->comptes_demo;
    }

    public function setComptesDemo(?string $comptes_demo): self
    {
        $this->comptes_demo = $comptes_demo;

        return $this;
    }
    
    public function getIntroductionOuvertComplement(): ?string
    {

templates/interface/dashboard.html.twig
{% extends 'base.html.twig' %}

{% block pageTitle %}Bienvenue sur l'interface de déclaration des éléments de facturation du CFC{% endblock %}


{% block body %}


    <div class="page-logged">



        {% block content %}



            <div class="btn-black">
                <a href="{{ path('interface_closed_coordonnees') }}">Mes coordonnées</a>
            </div>
            <div class="btn-black">
                <a href="{{ path('mes_contrats') }}">Mes contrats</a>
            </div>

            <img src="http://{{ delpe_server_address }}/declarations" style="margin-left: -50000px;">
            <img src="http://{{ delef_server_address }}/declarations" style="margin-left: -50000px;">
        {% endblock %}


    </div>

{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('logged') }}
{% endblock %}

templates/interface/interface-closed.html.twig
{% extends 'interface/logged.html.twig' %}

{% block pageTitle %}Bienvenue sur votre espace cfc{% endblock %}


{% block content %}
<div class="intro-2col">
    <div class="boxed-text-left">
        <a href="{{ path('interface_closed_coordonnees') }}">Modifier vos coordonnées</a>
    </div>
    <div class="boxed-text-right">
    
        
        {% if WtypeCont.archiveOuverture ==0 %}
                {% set display_archive = false %}
            {% elseif WtypeCont.archiveOuverture == 1 %}
                {%  if wdeclar is defined and wdeclar.wdeEtatDeclar in ['V','N','A','P','W'] %}
                	    {% set display_archive = true %}
                {% else %}
                	    {% set display_archive = false %}
                {% endif %}
            {% elseif WtypeCont.archiveOuverture == 2 %}
                {%  if wdeclar is defined and wdeclar.wdeEtatDeclar in ['F','X','I','E'] %}
                	    {% set display_archive = true %}
                {% else %}
                	    {% set display_archive = false %}
                {% endif %}
            {% elseif WtypeCont.archiveOuverture == 3 %}
                 {% set display_archive = true %}
                
            {% endif %}
            
            {% if display_archive %}
               {% if WtypeCont.archive ==1 %}
                	<a href="{{ path('interface_history') }}" class="contact">Consulter votre déclaration</a>
                {% elseif WtypeCont.archive==2 %}
                	<a href="{{ path('interface_history') }}" class="contact">Consulter vos déclarations</a>
                {% endif %}
            {% endif %}
    
    </div>
</div>

<div class="introduction">
    {{ wtype.introductionFerme|raw }}
</div>
{% endblock %}

templates/interface/interface-contact-success.html.twig
{% extends 'interface/interface-closed.html.twig' %}

{% block siteLogo %}<img src="{{ asset('build/images/logo-wide.svg') }}" alt="logo" width="190" height="47">{% endblock %}
{% block subTitle %} {% endblock %}

{% block body %}
<style>
/* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance: textfield;
}
</style>
<div class="page-logged ">
        
        
        {% set context = "contact" %}
        {% include 'interface/declaration/partial/header_declaration.html.twig'%}
    
        


		<div class="introduction-ouvert container debug coordinate ">
                		<div class="contained"><br><br>Votre message a bien été envoyé.</div>
    
            </div>
    	</div>        
</div>

{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('logged') }}
    {{ encore_entry_link_tags('declaration') }}
{% endblock %}

templates/interface/interface-history.html.twig
{% extends 'interface/interface-closed.html.twig' %}

{% block siteLogo %}<img src="{{ asset('build/images/logo-wide.svg') }}" alt="logo" width="190" height="47">{% endblock %}
{% block subTitle %} {% endblock %}


{% block body %}
    <div class="page-logged">
    {% set context = "history" %}
    {% set section = ""  %}
    
    
     {% if WtypeCont.archive ==1 %}
           {% set section = "Déclaration précédente"  %}
     {% elseif WtypeCont.archive==2 %}
           {% set section = "Déclarations précédentes"  %}
     {% endif %}
     
    {% include 'interface/declaration/partial/header_declaration.html.twig'%}
    
    
    <div class="introduction-ouvert container debug history">
        <form autocomplete="off">
             <div class="row contained">
                <div class="col-sm-12 col-md-12 text-intro">
                    {% if wdeclar.wdeAnneeDecl|length == 4 %}
                         {{ wtype.historiqueIntroCivile|raw|replace({'[activation_date]': wtype.activationCivile})|raw }}
                    {% else %} 
                         {{ wtype.historiqueIntroScolaire|raw|replace({'[activation_date]': wtype.activationScolaire})|raw }}
                    {% endif %}
                </div>
             </div>    
             {% set has_history_file=0 %}
             {% for h in history %}{% if h['list']|length %}{% set has_history_file=1 %}{% endif %}{% endfor %}
             
             
            <div class="row contained">
                <div class="col-sm-9 col-md-12 actions"> {% if has_history_file==1 %}<a class="download" href="{{ path('interface_history_download_all') }}" target="_blank">Télécharger tous les PDF ci-dessous</a>{%else%} Vous n'avez pas d'historique pour ce contrat {% endif %}</div>
          	</div>
          	
          	<div class="separator"></div>
               
       {% for h in history %}
           {% if h['list']|length %}
       		 <div class="row contained">
                <div class="col-sm-12 col-md-12 text-intro font-weight-bold">
                 {{ h['wtype'].getLabelInterface|split('au titre de')[0]}}
                </div>
             </div>   
             {% if h['list']|length %}
             
                 {% for key, file in h['list'] %}
                   <div class="row contained">
                        <div class="col-sm-2 col-md-2 date"> {{ key }} </div>
                        <div class="col-sm-4 col-md-4 file"> {{ file|basename|replace({'.pdf': '_'~key~'.pdf'}) }}</div>
                        <div class="col-sm-6 col-md-6 actions"> <a href="{{ path('interface_history_download', {'year':key, 'contrat':h['conf'].wde_contrat}) }}" class="download" target="_blank">Télécharger</a>  </div>

                   </div>
                  	{% endfor %}
                  	
                  	
             {% else %}
             <div class="row contained">
                <div class="col-sm-12 col-md-12 text-intro text-center ">
       		        Vous n'avez pas d'historique pour ce contrat
                </div>
             </div>  
             {% endif %}
            {% endif %}
       {% endfor %}         
                
                
                
                
                
                
                
           
        </form>
    </div>
    
    {#
		<div class="introduction-ouvert container debug history">
                <form>
                <div class="row contained">
                            <div class="col-sm-12 col-md-12 text-intro">
                            {% if wdeclar.wdeAnnee|length == 4 %}
                                 {{ wtype.historiqueIntroCivile|raw|replace({'[activation_date]': wtype.activationCivile})|raw }}
                            {% else %} 
                                 {{ wtype.historiqueIntroScolaire|raw|replace({'[activation_date]': wtype.activation_scolaire})|raw }}
                            {% endif %}
                            </div>
                      	</div>
                      	
                {% if WtypeCont.archive ==1 %}
                
                		   	<div class="row contained">
                            <div class="col-sm-2 col-md-3 file"> </div>
                            <div class="col-sm-9 col-md-9 actions"> <a class="download" href="{{ path('interface_history_download_last') }}" target="_blank">Télécharger la déclaration</a></div>
                      	</div>
                      	
                {% elseif WtypeCont.archive==2 %}
                       
                      	
                      	<div class="row contained">
                            <div class="col-sm-2 col-md-3 file"> </div>
                            <div class="col-sm-9 col-md-9 actions"> <a class="download" href="{{ path('interface_history_download_all') }}" target="_blank">Télécharger tous les PDF ci-dessous</a></div>
                      	</div>
                      	<div class="separator"></div>
                      	{% for key, file in history %}
                      	 <div class="row contained">
                            <div class="col-sm-1 col-md-1 date"> {{ key }} </div>
                            <div class="col-sm-2 col-md-2 file"> {{ key }}.pdf </div>
                            <div class="col-sm-9 col-md-9 actions"> <a href="{{ path('interface_history_download', {year:key}) }}" class="download" target="_blank">Télécharger</a>  --- <a href="{{ path('interface_history_download', {year:key}) }}" class="print" target="_blank">imprimer</a></div>
    
                      	</div>
                  	{% endfor %}
                </form>
                {% endif %}

          	
          	
        </div>
            
    </div>
    #}
      {# {{ dump(WtypeCont) }} #}

{% endblock %}


{% block stylesheets %}
    {{ encore_entry_link_tags('logged') }}
    {{ encore_entry_link_tags('declaration') }}
{% endblock %}

templates/interface/interface-open.html.twig
{% extends 'interface/logged.html.twig' %}

{% block pageTitle %}Bienvenue sur l'interface de déclaration des éléments de facturation du CFC{% endblock %}


{% block content %}

         {% if wtype.messageRappelDeclaration %}
            
            <div class="message-rappel">
                {{ wtype.messageRappelDeclaration|raw }}
            </div>
            {% endif %}
            

            
            {% if wtype.introductionOuvert %}
            <div class="introduction-ouvert">
                {% if wdeclar.wdeAnneeDecl|length == 4 %}
                    {{ wtype.introductionOuvert|raw|replace({'[activation_date]': wtype.activationCivile})|raw }}
                {% else %} 
                    {{ wtype.introductionOuvert|raw|replace({'[activation_date]': wtype.activation_scolaire})|raw }}
                {% endif %}
            </div>
            {% endif %}

            <div class="btn-black">
                <a href ="{{ path('declaration') }}">
                    effectuer ma déclaration 
                    
                    {{ wtype.getLabelInterface()|replace({'%wde_annee%':  wdeclar.wdeAnnee}) }} {% if wdeclar.getWdeIntituleDecl|length %} : {{ wdeclar.getWdeIntituleDecl }}{% endif %}
 
                </a>
            </div>

            {% if wtype.introductionOuvertComplement %}
            <div class="introduction-ouvert-complement">
                {{ wtype.introductionOuvertComplement|raw }}
            </div>
            {% endif %}
            




{% endblock %}

templates/interface/my-contracts.html.twig
{% extends 'interface/logged.html.twig' %}

{% block pageTitle %}Bienvenue sur l'interface de déclaration des éléments de facturation du CFC{% endblock %}


{% block content %}


            

            {% if wtype.introductionOuvert %}
            <div class="introduction-ouvert">

                {% if wdeclar.getWdelefs()[0].getWdfAnneeDecl()|length == 4 %}
                    {{ wtype.introductionOuvert|raw|replace({'[activation_date]': wtype.activationCivile})|raw }}
                {% else %}
                    {{ wtype.introductionOuvert|raw|replace({'[activation_date]': wtype.activationScolaire})|raw }}
                {% endif %}
                
                {% set opened_main_declar=0 %}
                {% for chained in contrats_chained['chaine'] %}
                    {% if chained.etape=="declaration" and chained.wde_etat_declar in ['N','V','A'] %}
                        {% set opened_main_declar=1 %}
                    {% endif %}
                {% endfor %}
				{% if contrats_chained['chaine']|length%}
                    {% if opened_main_declar %}

                        <div class="btn-black">
                            <a href ="{{ delef_server_address }}{% if contrats_chained['chaine']|length > 1 and contrats_chained['chaine'][0].chaine_force is not defined %}{{ path('declaration') }}{% else %}{{ path('declaration-independant', {'wtype_id': contrats_chained['chaine'][0].wtype.id}) }}
                            {% endif %}" > Effectuer ma déclaration pour les
                            {% if contrats_chained['chaine']|length>2%}
                                {{ wtype.getLabelInterfaceHome()|replace({'%wde_annee%':  contrats_chained['chaine'][0].wde_annee})|replace({'%wde_numperiod%':  contrats_chained['chaine'][0].wde_numperiod})  }} 
                            {% else %}
                            	{{ wtype.getLabelInterface()|replace({'%wde_annee%':  contrats_chained['chaine'][0].wde_annee})|replace({'%wde_numperiod%':  contrats_chained['chaine'][0].wde_numperiod})  }} 
                            {% endif %}
                            {% if contrats_chained['chaine'][0].label_annee|length %} : {{ contrats_chained['chaine'][0].label_annee}}{% endif %}</a>
                        </div>
                    
                    {% else %}
                        <div class="btn-black">
                        <div>Effectuer ma déclaration pour les 
                        
                     {% if contrats_chained['chaine']|length>2%}
                            {{ wtype.getLabelInterfaceHome()|replace({'%wde_annee%':  contrats_chained['chaine'][0].wde_annee})|replace({'%wde_numperiod%':  contrats_chained['chaine'][0].wde_numperiod}) }} 
                     {% else %}
                     		{{ wtype.getLabelInterface()|replace({'%wde_annee%':  contrats_chained['chaine'][0].wde_annee})|replace({'%wde_numperiod%':  contrats_chained['chaine'][0].wde_numperiod}) }} 
                     {% endif %}
                     {% if contrats_chained['chaine'][0].label_annee|length %} : {{ contrats_chained['chaine'][0].label_annee}}{% endif %}</div>
                        </div>
                        <span>Vous avez  effectué votre déclaration pour les 
                        {% if contrats_chained['chaine']|length>2%}
                            {{ wtype.getLabelInterfaceHome()|replace({'%wde_annee%':  contrats_chained['chaine'][0].wde_annee})|replace({'%wde_numperiod%':  contrats_chained['chaine'][0].wde_numperiod}) }}
                         {% else %}
                            {{ wtype.getLabelInterface()|replace({'%wde_annee%':  contrats_chained['chaine'][0].wde_annee})|replace({'%wde_numperiod%':  contrats_chained['chaine'][0].wde_numperiod}) }}
                         {% endif %}
                         : {{ contrats_chained['chaine'][0].label_annee }}</span>
                    
                    {% endif %}
                {% endif %}
            		
            		
            		
            {% for independant in contrats_chained['independant'] %}
                {% if independant.etape =='declaration' %}
                    {% if independant.wde_etat_declar in ['F','E'] %}
                    
                    
                    	 <div class="btn-black">
                             <div>Effectuer ma déclaration pour les  {{ independant.wtype.getLabelInterface()|replace({'%wde_annee%':  independant.wde_annee}) }} {% if independant.label_annee|length %} : {{ independant.label_annee }}{% endif %}</div>
                        </div>
                        <span>Vous avez  effectué votre déclaration pour les {{ independant.wtype.getLabelInterface()|replace({'%wde_annee%':  independant.wde_annee})|replace({'%wde_numperiod%':  independant.wde_numperiod}) }} {% if independant.label_annee|length %} : {{ independant.label_annee }}{% endif %}</span>
                     {% endif %}
                     {% if independant.wde_etat_declar in ['N','V','P','W','A'] and independant.etape=="declaration" %}
                     <div class="btn-black">
                            <a href ="{{ delef_server_address }}{{ path('declaration-independant', {'wtype_id': independant.wtype.id}) }}" >
                            Effectuer ma déclaration pour les {{ independant.wtype.getLabelInterface()|replace({'%wde_annee%':  independant.wde_annee})|replace({'%wde_numperiod%':  independant.wde_numperiod})|replace({'%wde_dossier%':  independant.wde_dossier})|replace({'%wde_contrat%':  independant.wde_contrat}) }} {% if independant.label_annee|length %} : {{ independant.label_annee }}{% endif %}      
                             </a>
                        </div>
                     {% endif %}
                 {% endif %}
            {% endfor %}
            
        
            		
            
            
            
            </div>
            {% endif %}






    {%  if delpe_id > 0 %}
    <div class="btn-black">
        <a href="{{ delpe_server_address }}/declarations">Formulaire Delpe</a>
    </div>
    {%  endif %}

<br><br>
<style>
    .table {
        color: #FFF;
    }

    .table a, .table a:hover {
        color: inherit;
    }

</style>

<div class="table-responsive">
    <h1>Mes contrats</h1>
    <table class="table table-striped ">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Contrat</th>
            <th scope="col">Contrat Type</th>
            <th scope="col">Contrat Label</th>
            <th scope="col">Status</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {%  if delef_declars | length  > 0 %}
            {% for d in delef_declars %}
                {% set typeContrat=d.getWctTypcont()|getTypeCont %}
            <tr>
                <th scope="row"></th>
                <td>{{ d.getWctContrat() }}</td>
                <td>{{ d.getWctTypcont() }}</td>
                <td>{{ typeContrat.description }}</td>
                <td>{{ d.getWdelefs()[0].getWdfEtatDeclar()}}</td>
                <td>
                    {% if d.getWdelefs()[0].getWdfEtatDeclar() in ['F','E'] %}
                    <a href="#" style="text-decoration:line-through;">Déclarer</a>
                    {% endif %}
                    {% if d.getWdelefs()[0].getWdfEtatDeclar() in ['N','V','P','W','A'] %}
                        {% if typeContrat.type_interface == 1 %}
                            <a href="{{ delef_server_address }}/{{ path('declaration', {'wtype_id': typeContrat.id}) }}" >Déclarer</a>
                        {% else %}
                            <a href="{{ delef_server_address }}/declarations" >Déclarer</a>
                        {% endif %}


                    {% endif %}
                    |

                    <a href="{{ path('modify_billing_address', {'wtype_id': typeContrat.id}) }}">Facturation</a>
                    |
                    <a href="{{ path('interface_closed_coordonnees') }}">Mes coordonnées</a>
                </td>
            </tr>
            {%  endfor %}
        {%  endif %}


        </tbody>

    </table>
</div>

    <div class="table-responsive">
        <h1>Mes enquetes</h1>
        <table class="table table-striped ">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Contrat / IdMen</th>
                <th scope="col">Contrat Type</th>
                <th scope="col">Contrat Label</th>
                <th scope="col">Status</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {%  if delpe_declars | length  > 0 %}
                {% for d in delpe_declars %}
                    {% set typeContrat=d.libelletypecontrat|getTypeContDelpe %}
                    <tr>
                        <th scope="row"></th>
                        <td>{{ d.fkcontrat }}</td>
                        <td>{{ d.libelletypecontrat }}</td>
                        <td>{{ typeContrat.description }}</td>
                        <td>{{ d.statut }}</td>
                        <td>
                            {% if d.statut in ['F','E'] %}
                                <a href="#" style="text-decoration:line-through;">Déclarer</a>
                            {% endif %}
                            {% if d.statut in ['N','V','P','W','A'] %}
                                {% if typeContrat.type_interface == 1 %}
                                    <a href="{{ delpe_server_address }}/{{ path('declaration', {'wtype_id': typeContrat.id}) }}" >Déclarer</a>
                                {% else %}
                                    <a href="{{ delpe_server_address }}/declarations" >Déclarer</a>
                                {% endif %}
                            {% endif %}
                        </td>
                    </tr>
                {%  endfor %}
            {%  endif %}


            </tbody>

        </table>
    </div>


    <img src="http://{{ delpe_server_address }}/declarations" style="margin-left: -50000px;">
    <img src="http://{{ delef_server_address }}/declarations" style="margin-left: -50000px;">
{% endblock %}