src/Entity/Wcocon.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Table;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Index;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WcoconRepository")
 * @Table(name="wcocon")
 */
class Wcocon implements UserInterface
{


    /**
     * @ORM\Column(type="datetime", nullable=false, options={"default": "CURRENT_TIMESTAMP"})
     * @ORM\Version
     */
    private $wco_stamp;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $wco_website;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $wco_synchro;

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     */
    private $wco_dossier;
    
    
    /**
     * @ORM\Column(type="string", length=8)
     */
    private $wco_password;

    /**
     * @ORM\Column(type="string", length=55, nullable=true)
     */
    private $wco_raisoc1;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_raisoc2;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_raisoc3;

    /**
     * @ORM\Column(type="string", length=6, nullable=true)
     */
    private $wco_numvoie;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_adresse1;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_adresse2;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_adresse3;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     */
    private $wco_copos;

    /**
     * @ORM\Column(type="string", length=42, nullable=true)
     */
    private $wco_ville;

    /**
     * @ORM\Column(type="string", length=8, nullable=true)
     */
    private $wco_siret;

    /**
     * @ORM\Column(type="string", length=26, nullable=true)
     */
    private $wco_tel;

    /**
     * @ORM\Column(type="string", length=26, nullable=true)
     */
    private $wco_fax;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $wco_email;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_president;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_nom_legal;

    /**
     * @ORM\Column(type="string", length=35, nullable=true)
     */
    private $wco_tit_legal;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_fct_legal;

    /**
     * @ORM\Column(type="string", length=90, nullable=true)
     */
    private $wco_entete;

    /**
     * @ORM\Column(type="string", length=4, nullable=true)
     */
    private $wco_typetabl;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $wco_mel_legal;

    

     /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $wco_tel_legal;
    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $wco_id_ct_legal;
    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $wco_id_ct_president;
    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $wco_id_adr_siege;




    private $sso_sync_data;
    private $delpe_id;

    
    
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Wcontrat", mappedBy="wctDossier", cascade={"all"}, orphanRemoval=false)
     */
    private $wcontrats;


    public function __construct()
    {
        //$this->wco_dossier = new ArrayCollection();
        $this->wcontrats = new ArrayCollection();
    }

    public function __toString()
    {
        return "Dossier ".$this->getWcoDossier();
    }
    

    public function getWcoStamp(): ?\DateTimeInterface
    {
        return $this->wco_stamp;
    }

    public function setWcoStamp(\DateTimeInterface $wco_stamp): self
    {
        $this->wco_stamp = $wco_stamp;

        return $this;
    }

    public function getWcoWebsite(): ?string
    {
        return $this->wco_website;
    }

    public function setWcoWebsite(?string $wco_website): self
    {
        $this->wco_website = $wco_website;

        return $this;
    }

    public function getWcoSynchro(): ?\DateTimeInterface
    {
        return $this->wco_synchro;
    }

    public function setWcoSynchro(?\DateTimeInterface $wco_synchro): self
    {
        $this->wco_synchro = $wco_synchro;

        return $this;
    }

    public function getWcoDossier(): ?int
    {
        return $this->wco_dossier;
    }

    public function setWcoDossier(int $wco_dossier): self
    {
        $this->wco_dossier = $wco_dossier;

        return $this;
    }

    public function getWcoPassword(): ?string
    {
        return $this->wco_password;
    }

    public function setWcoPassword(string $wco_password): self
    {
        $this->wco_password = $wco_password;

        return $this;
    }

    public function getWcoRaisoc1(): ?string
    {
        return $this->wco_raisoc1;
    }

    public function setWcoRaisoc1(?string $wco_raisoc1): self
    {
        $this->wco_raisoc1 = $wco_raisoc1;

        return $this;
    }

    public function getWcoRaisoc2(): ?string
    {
        return $this->wco_raisoc2;
    }

    public function setWcoRaisoc2(?string $wco_raisoc2): self
    {
        $this->wco_raisoc2 = $wco_raisoc2;

        return $this;
    }

    public function getWcoRaisoc3(): ?string
    {
        return $this->wco_raisoc3;
    }

    public function setWcoRaisoc3(?string $wco_raisoc3): self
    {
        $this->wco_raisoc3 = $wco_raisoc3;

        return $this;
    }

    public function getWcoNumvoie(): ?string
    {
        return $this->wco_numvoie;
    }

    public function setWcoNumvoie(?string $wco_numvoie): self
    {
        $this->wco_numvoie = $wco_numvoie;

        return $this;
    }

    public function getWcoAdresse1(): ?string
    {
        return $this->wco_adresse1;
    }

    public function setWcoAdresse1(?string $wco_adresse1): self
    {
        $this->wco_adresse1 = $wco_adresse1;

        return $this;
    }

    public function getWcoAdresse2(): ?string
    {
        return $this->wco_adresse2;
    }

    public function setWcoAdresse2(?string $wco_adresse2): self
    {
        $this->wco_adresse2 = $wco_adresse2;

        return $this;
    }

    public function getWcoAdresse3(): ?string
    {
        return $this->wco_adresse3;
    }

    public function setWcoAdresse3(?string $wco_adresse3): self
    {
        $this->wco_adresse3 = $wco_adresse3;

        return $this;
    }

    public function getWcoCopos(): ?string
    {
        return $this->wco_copos;
    }

    public function setWcoCopos(?string $wco_copos): self
    {
        $this->wco_copos = $wco_copos;

        return $this;
    }

    public function getWcoVille(): ?string
    {
        return $this->wco_ville;
    }

    public function setWcoVille(?string $wco_ville): self
    {
        $this->wco_ville = $wco_ville;

        return $this;
    }

    public function getWcoSiret(): ?string
    {
        return $this->wco_siret;
    }

    public function setWcoSiret(?string $wco_siret): self
    {
        $this->wco_siret = $wco_siret;

        return $this;
    }

    public function getWcoTel(): ?string
    {
        return $this->wco_tel;
    }

    public function setWcoTel(?string $wco_tel): self
    {
        $this->wco_tel = $wco_tel;

        return $this;
    }

    public function getWcoFax(): ?string
    {
        return $this->wco_fax;
    }

    public function setWcoFax(?string $wco_fax): self
    {
        $this->wco_fax = $wco_fax;

        return $this;
    }

    public function getWcoEmail(): ?string
    {
        return $this->wco_email;
    }

    public function setWcoEmail(?string $wco_email): self
    {
        $this->wco_email = $wco_email;

        return $this;
    }

    public function getWcoPresident(): ?string
    {
        return $this->wco_president;
    }

    public function setWcoPresident(?string $wco_president): self
    {
        $this->wco_president = $wco_president;

        return $this;
    }

    public function getWcoNomLegal(): ?string
    {
        return $this->wco_nom_legal;
    }

    public function setWcoNomLegal(?string $wco_nom_legal): self
    {
        $this->wco_nom_legal = $wco_nom_legal;

        return $this;
    }

    public function getWcoTitLegal(): ?string
    {
        return $this->wco_tit_legal;
    }

    public function setWcoTitLegal(?string $wco_tit_legal): self
    {
        $this->wco_tit_legal = $wco_tit_legal;

        return $this;
    }

    public function getWcoFctLegal(): ?string
    {
        return $this->wco_fct_legal;
    }

    public function setWcoFctLegal(?string $wco_fct_legal): self
    {
        $this->wco_fct_legal = $wco_fct_legal;

        return $this;
    }

    public function getWcoEntete(): ?string
    {
        return $this->wco_entete;
    }

    public function setWcoEntete(?string $wco_entete): self
    {
        $this->wco_entete = $wco_entete;

        return $this;
    }

    public function getWcoTypetabl(): ?string
    {
        return $this->wco_typetabl;
    }

    public function setWcoTypetabl(?string $wco_typetabl): self
    {
        $this->wco_typetabl = $wco_typetabl;

        return $this;
    }

    public function getWcoTelLegal(): ?string
    {
        return $this->wco_tel_legal;
    }
    
    public function setWcoTelLegal(?string $wco_tel_legal): self
    {
        $this->wco_tel_legal = $wco_tel_legal;
    
        return $this;
    }
    
    public function getWcoMelLegal(): ?string
    {

templates/interface/declaration/coordinate.html.twig
{% extends 'base.html.twig' %}

{% block siteLogo %}<img src="{{ asset('build/images/logo-wide.svg') }}" alt="logo" width="190" height="47">{% endblock %}
{% block subTitle %} {% endblock %}

{% block body %}
    <div class="page-logged coordinate">
    
        {% set context="coordinate" %}
        {% include 'interface/declaration/partial/header_declaration.html.twig'%}
        {% include 'interface/declaration/partial/breadcrumb.html.twig'%}
        
		<div class="introduction-ouvert container debug coordinate">
			<div class="form-title contained">METTRE À JOUR VOS COORDONNÉES</div>
			<div class="form-notice contained">* CHAMPS OBLIGATOIRES</div>
                {% include 'interface/declaration/partial/form.html.twig'%}
        </div>
            
    </div>

{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('logged') }}
    {{ encore_entry_link_tags('declaration') }}
{% endblock %}

templates/interface/declaration/declaration.html.twig
{% extends 'base.html.twig' %}

{% block siteLogo %}
    <img src="{{ asset('build/images/logo-wide.svg') }}" alt="logo" width="190" height="47">
{% endblock %}
{% block subTitle %} {% endblock %}

{% block body %}
    <style> 
.debug .red{border: solid 1px red}
.debug .blue{border: solid 1px blue}
.debug .green{border: solid 1px green}
.debug .yellow{border: solid 1px yellow}
 
.coordinate .nopadding, .declaration .nopadding {
   padding: 0 !important;
   margin: 0 !important;
}
.coordinate .nomargin, .declaration .nomargin {
    margin-right: 0px !important;
    margin-left: 0px !important;
}

.coordinate input, .coordinate select {
    display: table-cell;
   /* width: 100%;*/
}

.declaration input, .declaration select {
    max-width: 100px;
}
    
.coordinate input[type=radio],
.coordinate input.radio {
      width: auto;
    }
    
.declaration .font-weight-bold,
.declaration .title.font-weight-bold,
.declaration .sub-title.font-weight-bold 
     {
	font-family: 'Montserrat Bold';
}

.declaration .font-weight-light, .declaration .font-weight-normal{
	font-family: 'Montserrat';
}
.declaration .title, .declaration .label, .declaration .label-desc, .declaration .sub-title,
.coordinate .title, .coordinate .label, .coordinate .label-desc, .coordinate .sub-title,
.declaration .label-description, .declaration .label-description, .declaration .label-prefix,
.coordinate .label-description, .coordinate .label-description, .coordinate .label-prefix
{
	text-transform: uppercase;

}



</style>
<div class="page-logged declaration">
    
    {% set context = "declaration" %}
    {% include 'interface/declaration/partial/header_declaration.html.twig'%}
    
    {% include 'interface/declaration/partial/breadcrumb.html.twig'%}
    
    <div class="introduction-ouvert container debug declaration">
        {% include 'interface/declaration/partial/aide.html.twig'%}
        <div class="form-title contained">Effectuer votre déclaration<p>
            {{ conf[0].getWconfTypcont().getLabelInterface()|replace({'%wde_annee%':  conf[0].wde_annee})|replace({'%wde_numperiod%':  conf[0].wde_numperiod})|replace({'%wde_dossier%':  conf[0].wde_dossier})|replace({'%wde_contrat%':  conf[0].wde_contrat}) }}
        </div>
        <div class="form-notice contained">* CHAMPS OBLIGATOIRES</div>
            {% include 'interface/declaration/partial/form.html.twig'%}
    </div>
                   	                       			
</div>
</div>

{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('logged') }}
    {{ encore_entry_link_tags('declaration') }}
{% endblock %}

templates/interface/declaration/modification-billing-success.html.twig
{% extends 'base.html.twig' %}

{% block siteLogo %}
    <img src="{{ asset('build/images/logo-wide.svg') }}" alt="logo" width="190" height="47">
{% endblock %}

{% block body %}
<div class="page-logged">
    {% set context = "modification" %}
    {% include 'interface/declaration/partial/header_declaration.html.twig'%}

        
    <div class="success-message">
        <p><strong>LA MISE À JOUR DE VOS COORDONNÉES DE FACTURATION ON BIEN &Eacute;T&Eacute; PRISE EN COMPTE</strong></p>
        
        <p></p>
        
        <p></p>

    </div>
</div>
{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('logged') }}
    {{ encore_entry_link_tags('declaration') }}
{% endblock %}

templates/interface/declaration/modification-billing.html.twig
{% extends 'interface/interface-closed.html.twig' %}

{% block siteLogo %}<img src="{{ asset('build/images/logo-wide.svg') }}" alt="logo" width="190" height="47">{% endblock %}
{% block subTitle %} {% endblock %}

{% block body %}
    <div class="page-logged">
    {% set context = "modification" %}
    
    {% include 'interface/declaration/partial/header_declaration.html.twig'%}
    
		<div class="introduction-ouvert container debug coordinate ">
			<div class="form-title contained" contained>METTRE À JOUR VOS COORDONNÉES DE FACTURATION</div>
			<div class="form-notice contained">* CHAMPS OBLIGATOIRES</div>
                {% include 'interface/declaration/partial/form.html.twig'%}
        </div>
            
    </div>

{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('logged') }}
    {{ encore_entry_link_tags('declaration') }}
{% endblock %}

templates/interface/declaration/modification-coordinate-success.html.twig
{% extends 'base.html.twig' %}

{% block siteLogo %}
    <img src="{{ asset('build/images/logo-wide.svg') }}" alt="logo" width="190" height="47">
{% endblock %}

{% block body %}
<div class="page-logged">
    {% set context = "modification" %}
    {% include 'interface/declaration/partial/header_declaration.html.twig'%}

        
    <div class="success-message">
        <p><strong>LA MISE À JOUR DE VOS COORDONNÉES A BIEN &Eacute;T&Eacute; PRISE EN COMPTE</strong></p>
        
        <p></p>
        
        <p></p>

    </div>
</div>
{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('logged') }}
    {{ encore_entry_link_tags('declaration') }}
{% endblock %}

templates/interface/declaration/modification-coordinate.html.twig
{% extends 'interface/interface-closed.html.twig' %}

{% block siteLogo %}<img src="{{ asset('build/images/logo-wide.svg') }}" alt="logo" width="190" height="47">{% endblock %}
{% block subTitle %} {% endblock %}

{% block body %}
    <div class="page-logged">
    {% set context = "modification" %}
    
    {% include 'interface/declaration/partial/header_declaration.html.twig'%}
    
		<div class="introduction-ouvert container debug coordinate ">
			<div class="form-title contained" contained>METTRE À JOUR VOS COORDONNÉES</div>
			<div class="form-notice contained">* CHAMPS OBLIGATOIRES</div>
                {% include 'interface/declaration/partial/form.html.twig'%}
        </div>
            
    </div>

{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('logged') }}
    {{ encore_entry_link_tags('declaration') }}
{% endblock %}

templates/interface/declaration/pdf.html.twig
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    {% block stylesheets %}
        {{ encore_entry_link_tags('pdf_declar') }}
    {% endblock %}

    <style>
    {{bootstrap_css|raw}}
	</style>
	<style>

</style>
</head>
<body>

<br>
{% set pdf_image_title = "file://" ~  ROOT_DIR ~ '/public' ~ asset('build/images/title-separator-pdf.svg') %}

<htmlpageheader name="header">
    <div class="row" class="head">
    <div class="col col-md-2" style="width: 15%;"><img src="file://{{ ROOT_DIR }}/public{{ asset('build/images/logo-delef-pdf.svg') }}" alt="Logo" width="94" height="94"></div>
    <div class="col col-md-10 text-left head-text" style="width: 85%"> 
                <div class="title">DÉCLARATION EN LIGNE ANNÉE {{ primary_declaration.wdeAnnee }}</div>
                <div class="sub-title"><strong>{{ wcocon.wcoRaisoc1 }}</strong>  {{wcocon.wcoRaisoc2 }}  -
                <strong>Client n° :</strong> {{ wcocon.getWcoDossier }} <br>
                <strong>Contrat(s) n° :</strong>  {{ contrats|join(', ') }} </div>
    </div>
</htmlpageheader>

    {% set context = "pdf" %}
    {%   include 'interface/declaration/partial/form_validation.html.twig' %}

    <htmlpagefooter name="footer">
    
        <table width="100%" class="footer-content" style="vertical-align: bottom;">
            <tr>
                <td width="10%" ><span style="font-style: italic;">{DATE j-m-Y}</span></td>
                <td width="80%" align="center" style=""> © CENTRE FRANÇAIS D'EXPLOITATION DU DROIT DE COPIE (CFC) 2020 - www.cfcopies.com</td>
                <td width="10%" style="text-align: right; ">{PAGENO}/{nbpg}</td>
            </tr>
        </table>

    </htmlpagefooter>

</body>
</html>

templates/interface/declaration/validation-success.html.twig
{% extends 'base.html.twig' %}

{% block siteLogo %}
    <img src="{{ asset('build/images/logo-wide.svg') }}" alt="logo" width="190" height="47">
{% endblock %}
{% block subTitle %} {% endblock %}

{% block body %}
<div class="page-logged">
    {% set context ="declaration" %}
    {% include 'interface/declaration/partial/header_declaration.html.twig'%}

    {% include 'interface/declaration/partial/breadcrumb.html.twig' %}
        
    <div class="success-message">
        {{ wtype.validationConfirmMessage|raw }}
    </div>
</div>
{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('logged') }}
    {{ encore_entry_link_tags('declaration') }}
{% endblock %}

templates/interface/declaration/validation.html.twig
{% extends 'base.html.twig' %}

{% block siteLogo %}
    <img src="{{ asset('build/images/logo-wide.svg') }}" alt="logo" width="190" height="47">
{% endblock %}
{% block subTitle %} {% endblock %}

{% block body %}

<style>
<!--
.bottom-line{
	border-bottom: solid #006E96 1px;
}

.col-compos-title{
	max-width: 235px;
}
.col-compos-title-field{
	max-width: 300px;
}

.col-compos-num{
	max-width: 95px;
}
.col-compos-num-field{
	max-width: 80px;
}
.col-compos-button{
	max-width: 20px;
}

.add-compos{
	visibility: hidden;
}
.compos-line:nth-last-of-type(1) .add-compos{
	visibility: visible;
}

.compos-errors{
	color: red;
}

col-md-add-compos{
	visibility: hidden;
}
.compos-line:nth-last-of-type(1) .col-md-add-compos{
	visibility: visible;
}

.compos-errors{
	color: red;
}
.compos-title-field input{
	display: table-cell;
	max-width: 100%;
	width:100%;
}


@media screen and (min-width: 768px)
{
    .col-md-intitule-stage {
        flex-grow: 0;
        flex-shrink: 0;
        flex-basis: 195px;
    	max-width: 195px;
    }
   
    .col-md-intitule-stage-field{

        flex-grow: 0;
        flex-shrink: 0;
        flex-basis: 520px;
    	max-width: 520px;
    }
    .col-md-stagiaire{
	    flex-grow: 0;
        flex-shrink: 0;
        flex-basis: 195px;
    	max-width: 195px;
    }  
    
    .col-md-stagiaire-field{
	    flex-grow: 0;
        flex-shrink: 0;
        flex-basis: 170px;
    	max-width: 170px;
    } 
    
    .col-md-heures{
	    flex-grow: 0;
        flex-shrink: 0;
        flex-basis: 240px;
    	max-width: 240px;
    } 
    
    .col-md-heures-field{
	    flex-grow: 0;
        flex-shrink: 0;
        flex-basis: 100px;
    	max-width: 100px;
    }
    .col-md-remove-compos, .col-md-add-compos{
	    flex-grow: 0;
        flex-shrink: 0;
        flex-basis: 20px;
    	max-width: 20px;
    }

}


-->
</style>


<div class="page-logged">
    {% set context = "declaration" %}
    {% include 'interface/declaration/partial/header_declaration.html.twig'%}
    
    {% include 'interface/declaration/partial/breadcrumb.html.twig'%}
        
		<div class="introduction-ouvert container debug validation">
		<div class="container ">
          <div class="row">
            <div class="col-sm-12 col-md-10">ENVOYER VOTRE DÉCLARATION</div>
            <div class="col-sm-12 col-md-2 printer">
              <div class="icon-print"></div>
              <a href="href="#" onclick="window.print();return false;"">Imprimer</a>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12 col-md-12" >
                Dès que vous aurez confirmé les informations saisies, votre déclaration sera envoyée au CFC et vous recevrez un mail de confirmation.<br><br>
                <strong>Vérifiez bien votre déclaration</strong><br><br>             
			</div>
          </div>
        </div>
    	{{ form_start(form, {'attr':{"autocomplete":"off", "style":"margin-top: -70px;"}}) }}
    	
    	
    	<div class="container">
              <div class="row">
              	<div class="col-sm-12 col-md-12" >
                         <span style="color: red;">N'oubliez pas de cliquer sur le bouton « <strong>ENVOYER</strong> » pour <strong>CONFIRMER L'ENVOI</strong> de votre déclaration.</span><br><br><br>
                
					</div>
				</div>
				<div class="row" style="padding-bottom: 32px;">
                <div class="col-sm-12 col-md-10 "><div><button type="submit" id="form_submit" name="form[submit]">Envoyer</button></div><input type="hidden" id="form__token" name="form[_token]" value="_tl7xnlHsxL3Q2GFcV_egou2lR4deWO7ihmXiimLsh4"></div>
                <div class="col-sm-12 col-md-2 printer">&nbsp;</div>
              </div>
            </div>
    	
    	
    	
    	
    	    <div class="my-custom-class-for-errors">{{ form_errors(form) }}</div>
         

    	 
    	 
    	 
         {% include 'interface/declaration/partial/form_validation.html.twig'%}
         
         
         
         <div class="my-custom-class-for-errors">{{ form_errors(form) }}</div>
        
            <div class="container">
            <div class="row">
              	<div class="col-sm-12 col-md-12" >
                         <span style="color: red;">N'oubliez pas de cliquer sur le bouton « <strong>ENVOYER</strong> » pour <strong>CONFIRMER L'ENVOI</strong> de votre déclaration.</span><br><br><br>
                
					</div>
				</div>
              <div class="row">
                <div class="col-sm-12 col-md-10">{{ form_row(form.submit) }}{{ form_widget(form._token) }}</div>
                <div class="col-sm-12 col-md-2 printer">
                  <div class="icon-print"></div>
                  <a href="href="#" onclick="window.print();return false;"">Imprimer</a>
                </div>
              </div>
            </div>  
        
    	</form>
    		
    		
        </div>
</div>

{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('logged') }}
    {{ encore_entry_link_tags('declaration') }}
    {{ encore_entry_link_tags('validation') }}
{% endblock %}