src/Entity/Wcocon.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Table;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Index;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WcoconRepository")
 * @Table(name="wcocon")
 */
class Wcocon implements UserInterface
{


    /**
     * @ORM\Column(type="datetime", nullable=false, options={"default": "CURRENT_TIMESTAMP"})
     * @ORM\Version
     */
    private $wco_stamp;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $wco_website;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $wco_synchro;

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     */
    private $wco_dossier;
    
    
    /**
     * @ORM\Column(type="string", length=8)
     */
    private $wco_password;

    /**
     * @ORM\Column(type="string", length=55, nullable=true)
     */
    private $wco_raisoc1;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_raisoc2;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_raisoc3;

    /**
     * @ORM\Column(type="string", length=6, nullable=true)
     */
    private $wco_numvoie;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_adresse1;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_adresse2;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_adresse3;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     */
    private $wco_copos;

    /**
     * @ORM\Column(type="string", length=42, nullable=true)
     */
    private $wco_ville;

    /**
     * @ORM\Column(type="string", length=8, nullable=true)
     */
    private $wco_siret;

    /**
     * @ORM\Column(type="string", length=26, nullable=true)
     */
    private $wco_tel;

    /**
     * @ORM\Column(type="string", length=26, nullable=true)
     */
    private $wco_fax;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $wco_email;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_president;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_nom_legal;

    /**
     * @ORM\Column(type="string", length=35, nullable=true)
     */
    private $wco_tit_legal;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $wco_fct_legal;

    /**
     * @ORM\Column(type="string", length=90, nullable=true)
     */
    private $wco_entete;

    /**
     * @ORM\Column(type="string", length=4, nullable=true)
     */
    private $wco_typetabl;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $wco_mel_legal;

    

     /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $wco_tel_legal;
    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $wco_id_ct_legal;
    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $wco_id_ct_president;
    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $wco_id_adr_siege;




    private $sso_sync_data;
    private $delpe_id;

    
    
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Wcontrat", mappedBy="wctDossier", cascade={"all"}, orphanRemoval=false)
     */
    private $wcontrats;


    public function __construct()
    {
        //$this->wco_dossier = new ArrayCollection();
        $this->wcontrats = new ArrayCollection();
    }

    public function __toString()
    {
        return "Dossier ".$this->getWcoDossier();
    }
    

    public function getWcoStamp(): ?\DateTimeInterface
    {
        return $this->wco_stamp;
    }

    public function setWcoStamp(\DateTimeInterface $wco_stamp): self
    {
        $this->wco_stamp = $wco_stamp;

        return $this;
    }

    public function getWcoWebsite(): ?string
    {
        return $this->wco_website;
    }

    public function setWcoWebsite(?string $wco_website): self
    {
        $this->wco_website = $wco_website;

        return $this;
    }

    public function getWcoSynchro(): ?\DateTimeInterface
    {
        return $this->wco_synchro;
    }

    public function setWcoSynchro(?\DateTimeInterface $wco_synchro): self
    {
        $this->wco_synchro = $wco_synchro;

        return $this;
    }

    public function getWcoDossier(): ?int
    {
        return $this->wco_dossier;
    }

    public function setWcoDossier(int $wco_dossier): self
    {
        $this->wco_dossier = $wco_dossier;

        return $this;
    }

    public function getWcoPassword(): ?string
    {
        return $this->wco_password;
    }

    public function setWcoPassword(string $wco_password): self
    {
        $this->wco_password = $wco_password;

        return $this;
    }

    public function getWcoRaisoc1(): ?string
    {
        return $this->wco_raisoc1;
    }

    public function setWcoRaisoc1(?string $wco_raisoc1): self
    {
        $this->wco_raisoc1 = $wco_raisoc1;

        return $this;
    }

    public function getWcoRaisoc2(): ?string
    {
        return $this->wco_raisoc2;
    }

    public function setWcoRaisoc2(?string $wco_raisoc2): self
    {
        $this->wco_raisoc2 = $wco_raisoc2;

        return $this;
    }

    public function getWcoRaisoc3(): ?string
    {
        return $this->wco_raisoc3;
    }

    public function setWcoRaisoc3(?string $wco_raisoc3): self
    {
        $this->wco_raisoc3 = $wco_raisoc3;

        return $this;
    }

    public function getWcoNumvoie(): ?string
    {
        return $this->wco_numvoie;
    }

    public function setWcoNumvoie(?string $wco_numvoie): self
    {
        $this->wco_numvoie = $wco_numvoie;

        return $this;
    }

    public function getWcoAdresse1(): ?string
    {
        return $this->wco_adresse1;
    }

    public function setWcoAdresse1(?string $wco_adresse1): self
    {
        $this->wco_adresse1 = $wco_adresse1;

        return $this;
    }

    public function getWcoAdresse2(): ?string
    {
        return $this->wco_adresse2;
    }

    public function setWcoAdresse2(?string $wco_adresse2): self
    {
        $this->wco_adresse2 = $wco_adresse2;

        return $this;
    }

    public function getWcoAdresse3(): ?string
    {
        return $this->wco_adresse3;
    }

    public function setWcoAdresse3(?string $wco_adresse3): self
    {
        $this->wco_adresse3 = $wco_adresse3;

        return $this;
    }

    public function getWcoCopos(): ?string
    {
        return $this->wco_copos;
    }

    public function setWcoCopos(?string $wco_copos): self
    {
        $this->wco_copos = $wco_copos;

        return $this;
    }

    public function getWcoVille(): ?string
    {
        return $this->wco_ville;
    }

    public function setWcoVille(?string $wco_ville): self
    {
        $this->wco_ville = $wco_ville;

        return $this;
    }

    public function getWcoSiret(): ?string
    {
        return $this->wco_siret;
    }

    public function setWcoSiret(?string $wco_siret): self
    {
        $this->wco_siret = $wco_siret;

        return $this;
    }

    public function getWcoTel(): ?string
    {
        return $this->wco_tel;
    }

    public function setWcoTel(?string $wco_tel): self
    {
        $this->wco_tel = $wco_tel;

        return $this;
    }

    public function getWcoFax(): ?string
    {
        return $this->wco_fax;
    }

    public function setWcoFax(?string $wco_fax): self
    {
        $this->wco_fax = $wco_fax;

        return $this;
    }

    public function getWcoEmail(): ?string
    {
        return $this->wco_email;
    }

    public function setWcoEmail(?string $wco_email): self
    {
        $this->wco_email = $wco_email;

        return $this;
    }

    public function getWcoPresident(): ?string
    {
        return $this->wco_president;
    }

    public function setWcoPresident(?string $wco_president): self
    {
        $this->wco_president = $wco_president;

        return $this;
    }

    public function getWcoNomLegal(): ?string
    {
        return $this->wco_nom_legal;
    }

    public function setWcoNomLegal(?string $wco_nom_legal): self
    {
        $this->wco_nom_legal = $wco_nom_legal;

        return $this;
    }

    public function getWcoTitLegal(): ?string
    {
        return $this->wco_tit_legal;
    }

    public function setWcoTitLegal(?string $wco_tit_legal): self
    {
        $this->wco_tit_legal = $wco_tit_legal;

        return $this;
    }

    public function getWcoFctLegal(): ?string
    {
        return $this->wco_fct_legal;
    }

    public function setWcoFctLegal(?string $wco_fct_legal): self
    {
        $this->wco_fct_legal = $wco_fct_legal;

        return $this;
    }

    public function getWcoEntete(): ?string
    {
        return $this->wco_entete;
    }

    public function setWcoEntete(?string $wco_entete): self
    {
        $this->wco_entete = $wco_entete;

        return $this;
    }

    public function getWcoTypetabl(): ?string
    {
        return $this->wco_typetabl;
    }

    public function setWcoTypetabl(?string $wco_typetabl): self
    {
        $this->wco_typetabl = $wco_typetabl;

        return $this;
    }

    public function getWcoTelLegal(): ?string
    {
        return $this->wco_tel_legal;
    }
    
    public function setWcoTelLegal(?string $wco_tel_legal): self
    {
        $this->wco_tel_legal = $wco_tel_legal;
    
        return $this;
    }
    
    public function getWcoMelLegal(): ?string
    {

src/Entity/Wconf.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WconfRepository")
 */
class Wconf
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Wtype", inversedBy="id")
     * @ORM\JoinColumn( name="wconf_typcont", referencedColumnName="id", nullable=true, onDelete="SET NULL"))
     */
    private $wconf_typcont;

    /**
     * @ORM\Column(type="boolean",options={"default":0})
     */
    private $actif;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type_objet;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $label;

    /**
     * @ORM\Column(type="boolean",options={"default":0})
     */
    private $label_visible;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $etape;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $synchro_field;


    /**
     * ###@Gedmo\SortablePosition
     * @ORM\Column(type="integer")
     */
    private $position;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $type_objet_conf;

    /**
     * @ORM\Column(type="boolean",options={"default":0})
     */
    private $mandatory;

    /**
     * @ORM\Column(type="integer",options={"default":0})
     */
    private $validation_email;

    /**
     * @ORM\Column(type="boolean",options={"default":1})
     */
    private $affichage_espace_ferme;

    /**
     * @ORM\Column(type="boolean",options={"default":1})
     */
    private $facturation;

    public function __construct()
    {
        //$this->type = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getLabel();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function unsetId()
    {
        $this->id=null;
    }
    public function getWconfTypcont(): ?Wtype
    {
        return $this->wconf_typcont;
    }

    public function setWconfTypcont(?Wtype $wconf_typcont): self
    {
        $this->wconf_typcont = $wconf_typcont;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getTypeObjet(): ?string
    {
        return $this->type_objet;
    }

    public function setTypeObjet(?string $type_objet): self
    {
        $this->type_objet = $type_objet;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(?string $label): self
    {
        $this->label = $label;

        return $this;
    }


    public function getLabelVisible(): ?bool
    {
        return $this->label_visible;
    }

    public function setLabelVisible(bool $label_visible): self
    {
        $this->label_visible = $label_visible;

        return $this;
    }

    public function getEtape(): ?string
    {
        return $this->etape;
    }

    public function setEtape(?string $etape): self
    {
        $this->etape = $etape;

        return $this;
    }


    public function getSynchroField(): ?string
    {
        return $this->synchro_field;
    }

    public function setSynchroField(?string $synchro_field): self
    {
        $this->synchro_field = $synchro_field;

        return $this;
    }


    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getTypeObjetConf(): ?array
    {
        return !empty($this->type_objet_conf)?unserialize($this->type_objet_conf):[];
    }

    public function setTypeObjetConf(?array $type_objet_conf): self
    {
        $this->type_objet_conf = serialize($type_objet_conf);

        return $this;
    }

    public function getMandatory(): ?bool
    {
        return $this->mandatory;
    }

    public function setMandatory(bool $mandatory): self
    {
        $this->mandatory = $mandatory;

        return $this;
    }


    public function getValidationEmail(): ?int
    {
        return $this->validation_email;
    }

    public function setValidationEmail(int $validation_email): self
    {
        $this->validation_email = $validation_email;

        return $this;
    }

    public function getAffichageEspaceFerme(): ?bool
    {
        return $this->affichage_espace_ferme;
    }

    public function setAffichageEspaceFerme(bool $affichage_espace_ferme): self
    {
        $this->affichage_espace_ferme = $affichage_espace_ferme;

        return $this;
    }

    public function getFacturation(): ?bool
    {
        return $this->facturation;
    }

    public function setFacturation(bool $facturation): self
    {
        $this->facturation = $facturation;

        return $this;
    }
}

templates/interface/declaration/partial/field_file_upload.html.twig
{% set file_params=db_data['file_upload'][i.getSynchroField()] %}

<div class="row blue file-upload-row  contained">
		<div class="col-sm-12 col-md-12  label-description-container text-uppercase text-left"><span class="form-col-label label-description font-weight-bold text-uppercase">{{ i.label()|raw}}</span>
		
		<label for="file-upload-{{ i.id }}" class="custom-file-upload text-uppercase">Parcourir <i class="custom-file-upload-icon"></i></label>
        <input class="wabo_fichier file-upload-file-input" name="file_upload_file_input[{{ i.getSynchroField() }}]" id="file-upload-{{ i.id }}" type="file" placeholder=".xl, .xls" accept=".xlsx, .xls, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel, application/vnd.msexcel, text/csv" />
		<label class="custom-file-upload-filename"><input class="file-upload-filename-text" type="text" 
		
		placeholder=".xl .xls" style="" disabled=disabled
		data-extentions="{% if i.typeObjetConf.upload_file_extensions is defined %}{{i.typeObjetConf.upload_file_extensions}}{% endif %}"
		> <a class="delete_file" href="javascript:;" onclick="file_upload_reset_upload(this)"></a></label>
		
		<input type="hidden" name="file_upload_fichier_media_key[{{ i.getSynchroField() }}]" class="file-upload-fichier-media-key" value="{{ file_params['file_upload_fichier_media_key'] }}">
		<input type="hidden" name="file_upload_fichier_name[{{ i.getSynchroField() }}]" class="file-upload-fichier-name" value="{{ file_params['file_upload_fichier_name'] }}">
		
		</div>
</div>	

<div class="row blue contained">
		<div class="col-sm-12 col-md-12 text-center file-upload-notice">
		{% if i.typeObjetConf.upload_file_template_label is defined %}
		
            {% set upload_label= i.typeObjetConf.upload_file_template_label|raw %}

		    {% if i.typeObjetConf.upload_file_media_id is defined %}
			    {% set media_path=path('declaration_media_download', {'id': i.typeObjetConf.upload_file_media_id}) %}
			    {% set upload_label= upload_label | replace({'%link%': media_path}) %}
		    {% endif %}
			{{upload_label|raw}}
		
		{% endif %}
    	</div>
</div>

templates/interface/declaration/partial/fields_bon_commande.html.twig
{% if i.typeObjetConf.display_label_size is defined %}
    {% set grid_label = i.typeObjetConf.display_label_size %}
    {% set grid_form = 12-i.typeObjetConf.display_label_size %}
{% else %}    
    {% set grid_label = 2 %}
    {% set grid_form = 10 %}
{% endif %}

{% if i.typeObjetConf.label_style is defined %}
	{% set style = i.typeObjetConf.label_style %}
{% else %} 
	{% set style = "" %}
{% endif %}
              
              
{% if i.typeObjetConf.chorus_bdc_message is defined %}
    {% set chorus_bdc_message=i.typeObjetConf.chorus_bdc_message %}
{% else %}
    {% set chorus_bdc_message=false %}
{% endif %}          

<style>
.bon_commande{
	background-color: #E1EBF0;
	width: 100%;
	padding-top: 20px;
	padding-bottom: 20px;
	margin-bottom: 20px;
	margin-top: 20px;
}

#chorus_pro_bdc:required, #chorus_pro_service:required, #chorus_pro_siret:required {
  /**border: 1px solid red;
  outline: none;*/
}

input[name=wde_is_order_number]{
    width: 13px;
    margin-right: 7px;
    vertical-align: middle;
	margin-left: 15px;
}

</style>


<script>
jQuery(document).ready(function() {
if($('.bon-commande').length)	{
	$('#wdwde_is_order_number').on('click',function(){
		$('#wde_order_number').prop('required',true);
		$('.has_bdc_bloc, .bdc_bloc').show();
	})
	$('#wde_wde_is_order_number.on('click',function(){
		$('#wde_order_number').prop('required',false);
		$('#wde_order_number').val('');
		$('.has_bdc_bloc, .bdc_bloc').hide();
	})	

	if($('input[name=wde_is_order_number').val()==1)
	{
		$('#wde_order_number').prop('required',true);
		$('.has_bdc_bloc, .bdc_bloc').show();
	}else{
		$('.has_bdc_bloc, .bdc_bloc').hide();	
	}
}
});

</script>
<div class="bon-commande">

    <div class="row contained blue">
    	<div class="col-sm-12 col-md-9 nopadding  text-uppercase" style="">
    		<span class="form-col-label  label-description" style="">Un <strong>bon de commande / engagement</strong> doit-il figurer sur la facture ?</span>
    	</div>
    	<div class="col-sm-12 col-md-3 nopadding">
    		<div class="text-uppercase float-left">
    			<input type="radio" name="wde_is_order_number" id="wde_is_order_number_oui" {% if form.children['wde_is_order_number'].vars.value =="1" %}checked="checked"{% endif %} value="1" required="required"><label for="wde_is_order_number_oui">oui</label>
    			{#<input type="radio" name="wde_is_cwde_is_order_numberis_chowde_is_order_numberform.children['wde_is_choruwde_is_order_number=="1" %}checked="checked"{% endif %} value="1" required="required"><label for="wde_is_chorus_wde_is_order_number>#}
    		</div>
    		<div class="text-uppercase float-left">
    			<input type="radio" name="wde_is_order_number" id="wde_is_order_number_non" {% if form.children['wde_is_order_number'].vars.value =="0" %}checked="checked"{% endif %} value="0" required="required"><label for="wde_is_order_number_non">non</label>
			</div>
    			{#<input type="radio" name="wde_is_chorus_prwde_is_order_numbers_pro_wde_is_order_numberldren['wde_is_order_number'].wde_is_order_numberchecked="checked"{% endif %} value="0" required="required"><label for="wde_is_order_number_non"wde_is_order_number</div>#}
    	</div>
    	<ul class="error" style="font-weight: bold; color: red" id="err-wde_tit_resp"></ul>
    </div>

        {% if chorus_bdc_message is defined and chorus_bdc_message|raw|length %}	
            <div class="row contained blue has_bdc_bloc">
            	<div class="col-sm-12 col-md-12 nopadding chorus-message"> {{ chorus_bdc_message|raw  }}</div>
            </div>
           {% endif %}
           


	<div class="contained bdc_bloc">
    	<div class="row contained">
    	<div class="form-col-label  col-sm-12 col-md-{{ grid_label|replace({'.': '-'}) }} nopadding  text-uppercase {{ class }}"  style="{{ style }}><span class="label-description">{%if i.labelVisible == true %}{{ i.label()|raw }}{%if i.mandatory == true %}*{% endif %}{% endif %}</span></div>
    	<div class="form-col-fields col-sm-12 col-md-{{ grid_form|replace({'.': '-'}) }} nopadding"><input type="text"  
    	name="wde_order_number" 
		value="{{ form.children['wde_order_number'].vars.value }}" 
		id="wde_order_number" maxlength="50"
    	{%if i.mandatory == true %} required="required" {% endif %}
    	class="wppl_order_number"         
    	{% if i.typeObjetConf.not_empty_message is defined %}
        oninvalid="this.setCustomValidity('{{ i.typeObjetConf.not_empty_message|escape }}')"
        title='{{ i.typeObjetConf.not_empty_message|escape }}'
        {% endif %}
        oninput="this.setCustomValidity('')"></div>
	</div>
	</div>
</div>
    		

templates/interface/declaration/partial/fields_compos_stages.html.twig
<script>

{% if i.typeObjetConf.group_sum_id is defined %}
	var data_group_sum_id="{{ i.typeObjetConf.group_sum_id }}";
{% else %}
	var data_group_sum_id="";
{% endif %}

{% if i.typeObjetConf.group_sum_msg is defined %}
var data_group_sum_msg="{{ i.typeObjetConf.group_sum_msg }}";
{% else %}
var data_group_sum_msg="";
{% endif %}



{% if i.typeObjetConf.not_empty_alert is defined %}
var compos_stage_not_empty_alert="{{ i.typeObjetConf.not_empty_alert|escape }}";
{% else %}
var compos_stage_not_empty_alert=false;
{% endif %}


{% if i.typeObjetConf.wcompos_label_lien_supprimer is defined %}
var wcompos_label_lien_supprimer="{{ i.typeObjetConf.wcompos_label_lien_supprimer|escape }}";
{% else %}
var wcompos_label_lien_supprimer="Supprimer";
{% endif %}



var compos_stages_line ='<div class="row  compos-line contained">';
compos_stages_line+='<div class="col-sm-12 col-md-12 nopadding">';
compos_stages_line+='  <div class="row " style="margin-bottom: 10px !important">';
compos_stages_line+='		<div class="col-sm-12 col-md-intitule-stage text-uppercase nopadding text-left">INTITULÉ DU STAGE</div>';
compos_stages_line+='		<div class="col-sm-12 col-md-intitule-stage-field nopadding text-left compos-title-field"><input type="text" name="compos_title[]"  ></div>';
compos_stages_line+='	</div>';
compos_stages_line+='	<div class="row "  style="margin-bottom: 10px !important">';
compos_stages_line+='		<div class="col-sm-12 col-md-stagiaire text-uppercase nopadding text-left">NOMBRE DE STAGIAIRES</div>';
compos_stages_line+='		<div class="col-sm-12 col-md-stagiaire-field nopadding text-left compos-stagiaire-field"><input type="number" class="group_compos_stages_stagiaires" data-group-sum-id="'+data_group_sum_id+'" data-group-sum-msg="'+data_group_sum_msg+'" class="'+data_group_sum_id+'" min="1" max="99999" name="compos_stagiaires[]" onkeyup="calculatecompos_stages();" onkeydown="calculatecompos_stages();" oninput="calculatecompos_stages();" ></div>';
compos_stages_line+='		<div class="col-sm-12 col-md-heures text-uppercase text-left">NOMBRE D\'HEURES STAGIAIRES</div>';
compos_stages_line+='		<div class="col-sm-12 col-md-heures-field  text-left compos-heures-field"><input type="number" class="group_compos_stages_heures" data-group-sum-id="'+data_group_sum_id+'" data-group-sum-msg="'+data_group_sum_msg+'" class="'+data_group_sum_id+'" min="1" max="99999" name="compos_heures[]" onkeyup="calculatecompos_stages();" onkeydown="calculatecompos_stages();" oninput="calculatecompos_stages();"></div>';
compos_stages_line+='		<div class="col-sm-12 col-md-add-compos nopadding text-left"><a href="javascript:void(0);" onClick="addcompos_stages(this)" style="font-size:18">+</a></div>';
compos_stages_line+='		<div class="col-sm-12 col-md-remove-compos nopadding text-left "><a href="javascript:void(0);" onClick="removecompos_stages(this)" title="'+wcompos_label_lien_supprimer+'">X</a></div>';
compos_stages_line+='	</div>';
compos_stages_line+='</div>';
compos_stages_line+='</div>';




var compos_stages_data = [
	{% for compos in db_data.wcompos %}
	  {
		    label: "{{ compos.wcp_libelle|escape }}",
		    effectif: {{ compos.wcp_effectif|escape }},
		    heures: {{ compos.wcp_heures|escape }}
	  },
    {% endfor %}
	];
</script>
{% if form.children[i.synchroField()].vars.value is defined %}
    {% set form_value =  form.children[i.synchroField()].vars.value %}
{% else %}
    {% set form_value =  '' %}
{% endif %}
<div class="compos-stages">





</div>
<ul class="error compos-stages-errors contained" style="font-weight: bold;color:red" id="err-{{ i.synchroField() }}"></ul>

<div class="row compos-total-bloc contained">
		<div class="col-sm-12 col-md-8 nopadding text-right text-uppercase"><strong>Total stagiaires</strong></div>
		<div class="col-sm-12 col-md-1 nopadding text-center compos-total-bloc-total-stagiaires compos-total-bloc-blue">0</div>
		<div class="col-sm-12 col-md-2 nopadding text-right text-uppercase"><strong>Total heures&nbsp;</strong></div>
		<div class="col-sm-12 col-md-1 nopadding text-center compos-total-bloc-total compos-total-bloc-blue">0</div>
</div>
<div class="row compos-add-bloc contained">
		<div class="col-sm-12 col-md-12 nopadding text-right text-uppercase"> <a href="javascript:void(0);" onClick="addfirstcompos_stages()">Ajouter un stage</a></div>
</div>

templates/interface/declaration/partial/header-closed.html.twig
<style>
.active{
	font-weight: bold;
	color: white;
}
</style>

<div class="form-step">
    <div>
        <a href="{{ path('interface_closed_coordonnees') }}">Coordonnées</a>
    </div>
    <div>
        <a href="{{ path('interface_history') }}">
            {{ contrats|length > 1 ? 'Consulter vos déclarations' :  'Consulter votre déclaration' }}
        </a>
    </div>
</div>